name: Node.js CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: action/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-versions: "14"
    - run: npm install
    - run: npm test